"""create asset and currency tables

Revision ID: 4ec7b1bb971b
Revises: 4bb5be876af6
Create Date: 2026-02-17 13:32:29.751983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ec7b1bb971b'
down_revision: Union[str, Sequence[str], None] = '4bb5be876af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('rate_to_eur', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('asset',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK', 'CRYPTO', 'ETF', 'FOREX', 'COMMODITY', 'INDEX', name='assettype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_asset_ticker'), 'asset', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_ticker'), table_name='asset')
    op.drop_table('asset')
    op.drop_table('currency')
    # ### end Alembic commands ###
