"""add_history_and_dividends

Revision ID: de3073aee7a3
Revises: 5aae27044141
Create Date: 2026-02-24 23:05:13.556418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3073aee7a3'
down_revision: Union[str, Sequence[str], None] = '5aae27044141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividend_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('asset_ticker', sa.String(), nullable=False),
    sa.Column('amount_per_share', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_ticker'], ['asset.ticker'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['currency_code'], ['currency.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dividend_event_asset_ticker'), 'dividend_event', ['asset_ticker'], unique=False)
    op.create_index(op.f('ix_dividend_event_ex_date'), 'dividend_event', ['ex_date'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('asset_ticker', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_ticker'], ['asset.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_asset_ticker'), 'price_history', ['asset_ticker'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('asset_ticker', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAW', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('price_at_transaction', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('fees', sa.Numeric(precision=24, scale=10), server_default=sa.text('0'), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_ticker'], ['asset.ticker'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_asset_ticker'), 'transaction', ['asset_ticker'], unique=False)
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_portfolio_id'), 'transaction', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_date'), 'transaction', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_transaction_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_portfolio_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_asset_ticker'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_asset_ticker'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_dividend_event_ex_date'), table_name='dividend_event')
    op.drop_index(op.f('ix_dividend_event_asset_ticker'), table_name='dividend_event')
    op.drop_table('dividend_event')
    # ### end Alembic commands ###
